name: CI

on: push

jobs:
  krill_e2e_test_test:
    name: deploy_and_test
    runs-on: ubuntu-18.04
    steps:
    - name: Determine Krill branch to use
      id: pick_e2e_branch
      shell: bash
      run: |
        BRANCH=${GITHUB_REF#refs/heads/}
        if git ls-remote --exit-code --heads https://github.com/NLnetLabs/krill ${BRANCH}; then
          echo "::set-output name=branch::${BRANCH}"
        else
          echo "::set-output name=success::master"
        fi

    - name: Checkout E2E test framework
      uses: actions/checkout@v2
      with:
        path: rpki-deploy

    - name: Checkout Krill
      uses: actions/checkout@v2
      with:
        repository: nlnetlabs/krill
        path: krill
        ref: ${{ steps.pick_e2e_branch.outputs.branch }}

    - name: Checkout RTRLIB (v0.7.0 tag)
      uses: actions/checkout@v2
      with:
        repository: rtrlib/rtrlib
        ref: v0.7.0
        path: rtrlib

    - name: Install Python 3 venv package
      run: |
        set -x
        sudo apt-get update
        sudo apt-get install -y python3-venv

    - name: Install RTRLIB with NDEBUG
      working-directory: ./rtrlib
      run: |
        set -x
        cmake -D CMAKE_C_FLAGS='-DNDEBUG' -D CMAKE_BUILD_TYPE=Release -D RTRLIB_TRANSPORT_SSH=No .
        make
        sudo make install
        sudo ldconfig
  
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1.3.2
      with:
        terraform_version: "0.12.19"

    - name: Install Terraform plugins
      run: |
        set -x
        mkdir -p $HOME/.terraform.d/plugins/
        cp ${GITHUB_WORKSPACE}/rpki-deploy/terraform/plugins/terraform-provider-dockermachine $HOME/.terraform.d/plugins/

    - name: Print application versions
      run: |
        set -x
        docker --version
        docker-compose --version
        python3 --version
        terraform --version

    # Don't lock the state file, otherwise if the user cancels the build via the
    # GitHub Actions UI the terraform destroy cleanup step will fail.
    # Disable parallelism in Terraform to make logs more readable.
    - name: Deploy
      working-directory: ./rpki-deploy/terraform/krill-e2e-test/run_on_localhost
      timeout-minutes: 30
      run: |
        set -x
        terraform init
        terraform apply -lock=false -auto-approve -var "krill_build_path=${GITHUB_WORKSPACE}/krill"
      env:
        TF_VAR_run_tests: false

    - name: Run tests
      working-directory: ./rpki-deploy/terraform/krill-e2e-test/run_on_localhost
      run: |
        set -x
        terraform apply -auto-approve \
          -var "krill_build_path=${GITHUB_WORKSPACE}/krill" \
          -var "test_suite_path=${GITHUB_WORKSPACE}/krill/tests/e2e"
      env:
        TF_VAR_run_tests: true

    - name: Upload HTML test report
      uses: actions/upload-artifact@v1
      with:
        name: test-report
        path: /tmp/report.html

    - name: Dump diagnostics on failure
      if: failure()
      working-directory: ./rpki-deploy/terraform/krill-e2e-test/run_on_localhost
      run: |
        set -x
        terraform output docker_env_vars
        # eval $(terraform output docker_env_vars)
        pushd ../lib/docker
        docker logs krill
        docker system info
        docker system events --since 60m --until 1s

    - name: Undeploy
      if: always()
      working-directory: ./rpki-deploy/terraform/krill-e2e-test/run_on_localhost
      run: terraform destroy -auto-approve -var "krill_build_path=${GITHUB_WORKSPACE}/krill"
