name: CI

on: push

jobs:
  krill_e2e_test_test:
    name: deploy_and_test
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout Krill (master branch)
      uses: actions/checkout@v2
      with:
        repository: nlnetlabs/krill
        ref: master
        path: krill

    - name: Decrypt SSH key
      working-directory: ./rpki-deploy/terraform/krill-e2e-test
      run: |
        mkdir ${GITHUB_WORKSPACE}/secrets/
        echo "$SSH_KEY" > ${GITHUB_WORKSPACE}/secrets/ssh_key
        head -n 2 ${GITHUB_WORKSPACE}/secrets/ssh_key
        chmod 400 ${GITHUB_WORKSPACE}/secrets/ssh_key
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}

    - name: Deploy
      uses: nlnetlabs/rpki-deploy/run-tests@gh-docker-action
      with:
        ssh-key-path: ${GITHUB_WORKSPACE}/secrets/ssh_key
        do-token: ${{ secrets.DO_TOKEN }}
        mode: deploy

    - name: Run tests
      uses: nlnetlabs/rpki-deploy/run-tests@master
      with:
        ssh-key-path: ${GITHUB_WORKSPACE}/secrets/ssh_key
        do-token: ${{ secrets.DO_TOKEN }}
        mode: run-tests

    - name: Upload HTML test report
      uses: actions/upload-artifact@v1
      with:
        name: test-report
        path: ${GITHUB_WORKSPACE}/report.html

    - name: Undeploy
      if: always()
      uses: nlnetlabs/rpki-deploy/run-tests@master
      with:
        ssh-key-path: ${GITHUB_WORKSPACE}/secrets/ssh_key
        do-token: ${{ secrets.DO_TOKEN }}
        mode: undeploy
